"""updating model company

Revision ID: 78cfb2be8edb
Revises: eaaf9b5b0318
Create Date: 2026-02-26 03:01:41.011645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cfb2be8edb'
down_revision: Union[str, Sequence[str], None] = 'eaaf9b5b0318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('status', sa.Enum('active', 'inactive', name='companystatus'), nullable=False, server_default="active"))
    op.drop_column('companies', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('active', sa.VARCHAR(length=8), nullable=False))
    op.drop_column('companies', 'status')
    # ### end Alembic commands ###
