"""create company route, model, schema

Revision ID: eaaf9b5b0318
Revises: 9b28c1f9935e
Create Date: 2026-02-26 01:43:01.519049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaaf9b5b0318'
down_revision: Union[str, Sequence[str], None] = '9b28c1f9935e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('ramal', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Enum('active', 'inactive', name='companystatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('empresa_id', sa.Integer(), nullable=False))
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_foreign_key("fk_users_empresa", 'companies', ['empresa_id'], ['id'])
    # create_foreign_key(None, 'users', 'companies', ['empresa_id'], ['id'])
    # ### end Alembic commands ###S


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_empresa", 'users', type_='foreignkey')
    op.drop_column('users', 'empresa_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
